version: 2.1
# See: https://circleci.com/docs/2.0/configuration-reference
orbs:
  welcome: circleci/welcome-orb@0.4.1
# jobs:
#   print-hello:
#     docker:
#       - image: circleci/node:13.8.0
#     steps:
#       - run: echo "hello"

#   print-world:
#     docker:
#       - image: circleci/node:13.8.0
#     steps:
#       - run: echo "world" # echo $MY_ENV_VAR
# workflows:
#   welcome:
#     jobs:
#       - welcome/run
#       - print-hello
#       - print-world: 
#           requires:
#             - print-hello

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello world" > output.txt
      - persist_to_workspace:
          root: .
          paths:
            - output.txt
            
  print_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: .
      - run: cat output.txt

workflows:
  build_and_test:
    jobs:
      - save_hello_world_output
      - print_hello_world_output:
          requires:
            - save_hello_world_output

