version: 2.1
# See: https://circleci.com/docs/2.0/configuration-reference
orbs:
  welcome: circleci/welcome-orb@0.4.1
# jobs:
#   print-hello:
#     docker:
#       - image: circleci/node:13.8.0
#     steps:
#       - run: echo "hello"

#   print-world:
#     docker:
#       - image: circleci/node:13.8.0
#     steps:
#       - run: echo "world" # echo $MY_ENV_VAR
# workflows:
#   welcome:
#     jobs:
#       - welcome/run
#       - print-hello
#       - print-world: 
#           requires:
#             - print-hello

#---------------------------------------------SAVE TO A TXT FILE

# jobs:
#   save_hello_world_output:
#     docker:
#       - image: circleci/node:13.8.0
#     steps:
#       - run: echo "hello world" > output.txt # ~/output.txt
#       - persist_to_workspace:
#           root: .  # ~/
#           paths:
#             - output.txt

#   print_hello_world_output:
#     docker:
#       - image: circleci/node:13.8.0
#     steps:
#       - attach_workspace:
#           at: .  # ~/
#       - run: cat output.txt  # ~/output.txt

# workflows:
#   build_and_test:
#     jobs:
#       - save_hello_world_output
#       - print_hello_world_output:
#           requires:
#             - save_hello_world_output

#-------------------------------------------DRY using COMMANDS

commands:
  print_pipeline_id:
    parameters:
      id:
        type: string
    steps:
      - run: echo "<< parameters.id >>"

jobs:
  my_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id:
          id: << pipeline.id >>

workflows:
  my_workflow:
    jobs:
      - my_job

#-------------------------------------------Deliberate Failure

# jobs:
#   my_job:
#     docker:
#       - image: circleci/node:13.8.0
#     steps:
#       - run: exit 1
#       - run:
#           name: "This step will not run"
#           command: echo "Told ya it would fail"
#           when: on_fail

# workflows:
#   my_workflow:
#     jobs:
#       - my_job




